dist: trusty
group: deprecated-2017Q4
language: java
sudo: true
env:
  - headless=true
jdk:
  - openjdk8
services:
  - postgresql
addons:
  chrome: stable
  postgresql: "9.6"
  apt:
    packages:
      - postgresql-server-dev-9.6
before_install:
  - gradle wrapper
  - echo "hello world"
  - printenv
  - which psql
  - sudo apt-get install postgresql-server-dev-9.6
  - git clone https://github.com/eulerto/wal2json.git
  - cd wal2json && USE_PGXS=1 make && sudo USE_PGXS=1 make install && cd ..
  - ls -l /etc/postgresql/9.6/main/postgresql.conf
  - echo "max_wal_senders = 4" | sudo tee -a /etc/postgresql/9.*/main/postgresql.conf
  - echo "wal_keep_segments = 4" | sudo tee -a /etc/postgresql/9.*/main/postgresql.conf
  - echo "wal_level = logical" | sudo tee -a /etc/postgresql/9.*/main/postgresql.conf
  - echo "max_replication_slots = 4" | sudo tee -a /etc/postgresql/9.*/main/postgresql.conf
  - echo "local replication postgres peer" | sudo tee -a /etc/postgresql/9.6/main/pg_hba.conf
  - echo "host replication postgres 127.0.0.1/32 md5" | sudo tee -a /etc/postgresql/9.6/main/pg_hba.conf
  - echo "host replication postgres ::1/128 md5" | sudo tee -a /etc/postgresql/9.6/main/pg_hba.conf
  - sudo service postgresql restart
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
install:
  - pwd
  - ls -la
  - wget -N http://chromedriver.storage.googleapis.com/2.33/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
  - ./gradlew build -x test
before_script:
  - sudo -u postgres psql -U postgres -d postgres -c "alter user postgres with password 'postgres';"
script:
  - which chromedriver
  - ./gradlew build
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
