language: java
sudo: true
jdk:
  - oraclejdk8
services:
  - postgresql
addons:
  postgresql: "9.6"
  apt:
    packages:
      - oracle-java8-installer
      - postgresql-server-dev-9.6
before_install:
  - gradle wrapper
  - echo "hello world"
  - printenv
  - which psql
  - sudo apt-get install postgresql-server-dev-9.6
  - git clone https://github.com/eulerto/wal2json.git
  - cd wal2json && USE_PGXS=1 make && sudo USE_PGXS=1 make install && cd ..
  - ls -l /etc/postgresql/9.6/main/postgresql.conf
  - echo "max_wal_senders = 4" | sudo tee -a /etc/postgresql/9.*/main/postgresql.conf
  - echo "wal_keep_segments = 4" | sudo tee -a /etc/postgresql/9.*/main/postgresql.conf
  - echo "wal_level = logical" | sudo tee -a /etc/postgresql/9.*/main/postgresql.conf
  - echo "max_replication_slots = 4" | sudo tee -a /etc/postgresql/9.*/main/postgresql.conf
  - sudo service postgresql restart
install:
  - pwd
  - ls -la
  - mvn dependency:resolve
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - mvn verify
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
