apiVersion: v1
kind: Service
metadata:
  name: pgrepl-service
  labels:
    app: pgrepl
    tier: frontend
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: pgrepl
    tier: frontend
---
apiVersion: v1beta1
kind: Deployment
metadata:
  name: pgrepl-deployment
spec:
  type: LoadBalancer
  replicas: 1
  template:
    metadata:
      labels:
        app: pgrepl
        tier: frontend
    spec:
      containers:
      - name: pgrepl
        image: bgard6977/pgrepl  # or just image: redis
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080
