CREATE TABLE PERSON (
  ID       INT               NOT NULL,
  NAME     VARCHAR           NOT NULL,
  curTxnId CHARACTER VARYING NOT NULL,
  prvTxnId CHARACTER VARYING
);
ALTER TABLE person
  REPLICA IDENTITY FULL;